from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1740, 948)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabs_on_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs_on_main.setObjectName("tabs_on_main")
        self.workspace = QtWidgets.QWidget()
        self.workspace.setObjectName("workspace")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.workspace)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_col = QtWidgets.QWidget(self.workspace)
        self.left_col.setMinimumSize(QtCore.QSize(200, 0))
        self.left_col.setMaximumSize(QtCore.QSize(250, 16777215))
        self.left_col.setStyleSheet("")
        self.left_col.setObjectName("left_col")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_col)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_left_col_view = QtWidgets.QLabel(self.left_col)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_left_col_view.sizePolicy().hasHeightForWidth())
        self.label_left_col_view.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_left_col_view.setFont(font)
        self.label_left_col_view.setScaledContents(False)
        self.label_left_col_view.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_left_col_view.setObjectName("label_left_col_view")
        self.verticalLayout_2.addWidget(self.label_left_col_view)
        self.left_col_view = QtWidgets.QWidget(self.left_col)
        self.left_col_view.setStyleSheet("background-color: rgb(212, 212, 212)")
        self.left_col_view.setObjectName("left_col_view")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_col_view)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pref_edit_1 = QtWidgets.QGroupBox(self.left_col_view)
        self.pref_edit_1.setObjectName("pref_edit_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pref_edit_1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pref_2 = QtWidgets.QWidget(self.pref_edit_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pref_2.sizePolicy().hasHeightForWidth())
        self.pref_2.setSizePolicy(sizePolicy)
        self.pref_2.setObjectName("pref_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.pref_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_pref_2 = QtWidgets.QLabel(self.pref_2)
        self.label_pref_2.setObjectName("label_pref_2")
        self.horizontalLayout_5.addWidget(self.label_pref_2)
        self.ch_pref_2 = QtWidgets.QCheckBox(self.pref_2)
        self.ch_pref_2.setObjectName("ch_pref_2")
        self.horizontalLayout_5.addWidget(self.ch_pref_2)
        self.verticalLayout_4.addWidget(self.pref_2)
        self.pref_1 = QtWidgets.QWidget(self.pref_edit_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pref_1.sizePolicy().hasHeightForWidth())
        self.pref_1.setSizePolicy(sizePolicy)
        self.pref_1.setObjectName("pref_1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.pref_1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_pref_1 = QtWidgets.QLabel(self.pref_1)
        self.label_pref_1.setObjectName("label_pref_1")
        self.horizontalLayout_3.addWidget(self.label_pref_1)
        self.ch_pref_1 = QtWidgets.QCheckBox(self.pref_1)
        self.ch_pref_1.setObjectName("ch_pref_1")
        self.horizontalLayout_3.addWidget(self.ch_pref_1)
        self.verticalLayout_4.addWidget(self.pref_1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.pref_edit_1)
        self.verticalLayout_2.addWidget(self.left_col_view)
        self.horizontalLayout_2.addWidget(self.left_col)
        self.line = QtWidgets.QFrame(self.workspace)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.right_col = QtWidgets.QWidget(self.workspace)
        self.right_col.setMinimumSize(QtCore.QSize(600, 600))
        self.right_col.setObjectName("right_col")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_col)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_right_col_view = QtWidgets.QLabel(self.right_col)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_right_col_view.sizePolicy().hasHeightForWidth())
        self.label_right_col_view.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_right_col_view.setFont(font)
        self.label_right_col_view.setScaledContents(False)
        self.label_right_col_view.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_right_col_view.setObjectName("label_right_col_view")
        self.verticalLayout.addWidget(self.label_right_col_view)
        self.right_view = QtWidgets.QWidget(self.right_col)
        self.right_view.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.right_view.setObjectName("right_view")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.right_view)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_5 = QtWidgets.QWidget(self.right_view)
        self.widget_5.setMinimumSize(QtCore.QSize(100, 100))
        self.widget_5.setMaximumSize(QtCore.QSize(100, 100))
        self.widget_5.setStyleSheet("background-color: rgb(120, 120, 120)")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_6.addWidget(self.widget_5)
        self.line_2 = QtWidgets.QFrame(self.right_view)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_6.addWidget(self.line_2)
        self.widget_4 = QtWidgets.QWidget(self.right_view)
        self.widget_4.setMinimumSize(QtCore.QSize(100, 100))
        self.widget_4.setMaximumSize(QtCore.QSize(100, 100))
        self.widget_4.setStyleSheet("background-color: rgb(120, 120, 120)")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6.addWidget(self.widget_4)
        self.line_3 = QtWidgets.QFrame(self.right_view)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.widget = QtWidgets.QWidget(self.right_view)
        self.widget.setMinimumSize(QtCore.QSize(100, 100))
        self.widget.setMaximumSize(QtCore.QSize(100, 100))
        self.widget.setStyleSheet("background-color: rgb(120, 120, 120)")
        self.widget.setObjectName("widget")
        self.horizontalLayout_6.addWidget(self.widget)
        self.line_4 = QtWidgets.QFrame(self.right_view)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.widget_2 = QtWidgets.QWidget(self.right_view)
        self.widget_2.setMinimumSize(QtCore.QSize(100, 100))
        self.widget_2.setMaximumSize(QtCore.QSize(100, 100))
        self.widget_2.setStyleSheet("background-color: rgb(120, 120, 120)")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_6.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.right_view)
        self.horizontalLayout_2.addWidget(self.right_col)
        self.tabs_on_main.addTab(self.workspace, "")
        self.output = QtWidgets.QWidget()
        self.output.setObjectName("output")
        self.tabs_on_main.addTab(self.output, "")
        self.horizontalLayout.addWidget(self.tabs_on_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1740, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs_on_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_left_col_view.setText(_translate("MainWindow", "Model Prefs"))
        self.pref_edit_1.setTitle(_translate("MainWindow", "Prefs"))
        self.label_pref_2.setText(_translate("MainWindow", "Par 1"))
        self.ch_pref_2.setText(_translate("MainWindow", "123"))
        self.label_pref_1.setText(_translate("MainWindow", "Par 2"))
        self.ch_pref_1.setText(_translate("MainWindow", "123"))
        self.label_right_col_view.setText(_translate("MainWindow", "View model"))
        self.tabs_on_main.setTabText(self.tabs_on_main.indexOf(self.workspace), _translate("MainWindow", "Workspace"))
        self.tabs_on_main.setTabText(self.tabs_on_main.indexOf(self.output), _translate("MainWindow", "Output"))
        self.menu.setTitle(_translate("MainWindow", "model"))
        self.action.setText(_translate("MainWindow", "Start Sim"))
        self.action_2.setText(_translate("MainWindow", "Stom sim"))
